version: "3.8"
services:

    # PHP Service
    php:
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
        depends_on:
            database:
                condition: service_healthy

    # Database Server
    database:
        container_name: ${DB_DATABASE}
        image: bitnami/mariadb:latest
        ports:
            -   3306:3306
        environment:
            - MARIADB_DATABASE=${DB_DATABASE}
            - MARIADB_ROOT_USER=${DB_USERNAME}
            - MARIADB_PASSWORD=${DB_PASSWORD}
            - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
            - MARIADB_HOST=${DB_HOST}
        volumes:
            - db-data:/var/lib/mysql
        healthcheck:
            test: "mysql -u${DB_USERNAME} -p${DB_PASSWORD} -e 'show databases;'"
            interval: 2s
            retries: 120

    # Node Server
    node:
        build:
            context: .
            target: node
        volumes:
            - .:/usr/src
            - ./node_modules:/usr/src/node_modules
        tty: true

volumes:
    db-data: ~
